### ISSUE TITLE
Hotfix needed, administrate reviews/comments not rendering on dashboard. Related to permissions

### ISSUE THREAD

**Issue by daniel-salin** [chas-academy/09-imdb-clone-team-genius#149] opened 2019-04-10 13:49 UTC
hasPermissions('browse_reviews')
hasPermissions('browse_comments')

Does not work, probably since the permissions table seeder did not include them. No idea why this suddenly became an issue since it has worked before.

**Comment by ChristianBlom84** [comment] 2019-04-10 20:53
Works for me, did you check the role_id on the user you're logged in as? It defaults to 2, which is a normal user that doesn't have permission.

**Comment by ChristianBlom84** [comment] 2019-04-10 20:54
There could be an issue if you've done a migrate:fresh and didn't seed the Voyager data. If you haven't, maybe try runnin php artisan db:seed --class=VoyagerDatabaseSeeder?

**Comment by ChristianBlom84** [comment] 2019-04-11 11:08
Closing this, the issue is BREAD need to be added to the tables in Voyager.

**Closed as completed by ChristianBlom84** 2019-04-11 11:08 UTC
Labels: bug
